# Generated by Django 5.0.2 on 2026-04-25 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0016_merge_20260327_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringorder',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
