# Generated by Django 5.0.2 on 2026-05-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0024_merge_20260505_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='account_type',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMMUNITY_GROUP', 'Community Group')], default='INDIVIDUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='organisation_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='special_instructions',
            field=models.TextField(blank=True),
        ),
    ]
