# Generated by Django 5.0.2 on 2026-05-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0026_drop_special_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='delivery_instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
