from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/profiles/', views.admin_profiles, name='admin_profiles'),
    path('dashboard/orders/', views.admin_orders, name='admin_orders'),
    path('dashboard/reports/', views.admin_reports, name='admin_reports'),
    path('dashboard/reports/export/pdf/', views.download_admin_report_pdf, name='download_admin_report_pdf'),
    path('signup/', views.signup_choice, name='signup_choice'),
    path('signup/producer/', views.signup_producer, name='signup_producer'),
    path('signup/customer/', views.signup_customer, name='signup_customer'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('login/', auth_views.LoginView.as_view(template_name='marketplace/login.html'), name='login'),
    path('products/add/', views.add_product, name='add_product'),
    path('market/', views.customer_market, name='customer_market'),
    path('producer/bio/', views.producer_bio, name='producer_bio'),
    path('producers/<int:producer_id>/', views.producer_bio_public, name='producer_bio_public'),
    path('products/<int:product_id>/', views.producer_product_actions, name='producer_product_actions'),
    path('products/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
    path('basket/add/<int:product_id>/', views.add_to_basket, name='add_to_basket'),
    path('basket/', views.view_basket, name='view_basket'),
    path('basket/remove/<int:item_id>/', views.remove_from_basket, name='remove_from_basket'),
    path('basket/checkout/', views.checkout, name='checkout'),
    path('orders/<int:order_id>/confirmation/', views.order_confirmation, name='order_confirmation'),
    path('orders/', views.order_history, name='order_history'),
    path('orders/items/<int:order_item_id>/review/', views.submit_product_review, name='submit_product_review'),
    path('orders/<int:order_id>/reorder/', views.reorder, name='reorder'),
    path('orders/<int:order_id>/receipt/', views.download_receipt, name='download_receipt'),
    path('producer/orders/', views.producer_orders, name='producer_orders'),
    path('producer/reviews/', views.producer_reviews, name='producer_reviews'),
    path('producer/orders/<int:order_id>/update/', views.update_order_status, name='update_order_status'),
    path('producer/settlements/', views.payment_settlements, name='payment_settlements'),
    path('producer/settlements/<str:week_start_str>/pdf/', views.download_settlement_pdf, name='download_settlement_pdf'),
    path('orders/recurring/setup/', views.setup_recurring_order, name='setup_recurring_order'),
    path('orders/recurring/cancel/', views.cancel_recurring_setup, name='cancel_recurring_setup'),
    path('orders/recurring/', views.manage_recurring_orders, name='manage_recurring_orders'),
    path('orders/recurring/<int:recurring_order_id>/update/', views.update_recurring_order_status, name='update_recurring_order_status'),
    path('notifications/', views.notifications, name='notifications'),
]